# Server configuration
server.port=5000

# Database configuration
spring.datasource.url=jdbc:postgresql://1Panel-postgresql-eMzN:5432/blog
spring.datasource.username=xiaojiu
spring.datasource.password=xiaojiu

# JPA configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT configuration
jwt.secret=HsJn6b7LDU8HoSiR1iS1+CG/f7e8dW8kqy7pkz6LSrs=
jwt.expiration=86400000
jwt.refresh.expiration=604800000